export const APP_ROUTES = {
  HOME: '/',
  HOME_PATH: '/:key?',
  LOGIN: '/login/',
  LOGIN_PATH: '/login/:key?',
  SIGNUP: '/signup/',
  SIGNUP_PATH: '/signup/:key?',
  FORGOT_PASSWORD: '/forgotpassword/',
  RESET_PASSWORD_PATH: '/resetpassword/:token',
  VERIFY_PATH: '/verify/:token',
  POKERBOARD: '/pokerboard/',
  POKERBOARD_PATH: '/pokerboard/:id',
  POKER_CONFIGURE: '/pokerboard/configure',
  POKER_TICKETS: '/pokerboard/:id/tickets',
  POKER_INVITES: '/pokerboard/:id/invite',
  JIRA_AUTH: '/jira/add/user',
  ESTIMATION_GAME: '/estimation/pokerboard/',
  ESTIMATION_GAME_PATH: '/estimation/pokerboard/:pokerboard_id/',
  CREATE_GROUP: '/groups/create',
};
