export const CONSTANTS = {
  GROUP_NAME_MAX_LENGTH: 100,
  POKERBOARD_NAME_MAX_LENGTH: 100,
  ESTIMATION_TIME_MAX_LIMIT: 600,
  ESTIMATION_TIME_MIN_LIMIT: 10,
  USER_PASSWORD_MAX_LENGTH: 128,
  USER_PASSWORD_MIN_LENGTH: 8,
  USER_FIRST_NAME_MAX_LENGTH: 100,
  USER_LAST_NAME_MAX_LENGTH: 30,
};
