# Generated by Django 2.2.10 on 2023-04-22 11:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jira_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jirauser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='jira_credentials', to=settings.AUTH_USER_MODEL),
        ),
    ]
