# Generated by Django 2.2.10 on 2023-04-16 06:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PokerBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(help_text='Description of board')),
                ('status', models.SmallIntegerField(choices=[(0, 'created'), (1, 'started'), (2, 'finished')], default=0, help_text='Status of the board: [created | started | finished]')),
                ('estimation_time', models.PositiveIntegerField(help_text='Time in seconds')),
                ('estimation_type', models.SmallIntegerField(choices=[(0, 'Odd'), (1, 'Even'), (2, 'Fibonacci'), (3, 'Custom')], default=0)),
                ('manager', models.ForeignKey(help_text='Only owner of the board', on_delete=django.db.models.deletion.CASCADE, related_name='owned_boards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PokerBoardUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_role', models.SmallIntegerField(choices=[(1, 'Spectator'), (0, 'Participant')], default=0)),
                ('poker_board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='poker_boards.PokerBoard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('poker_board', 'user')},
            },
        ),
        migrations.AddField(
            model_name='pokerboard',
            name='users',
            field=models.ManyToManyField(related_name='participated_boards', through='poker_boards.PokerBoardUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
