# Generated by Django 2.2.10 on 2023-04-16 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('type', models.IntegerField(choices=[(0, 'sign up token'), (1, 'poker board invitation'), (2, 'change password')])),
                ('status', models.IntegerField(choices=[(0, 'invited'), (1, 'accepted'), (2, 'rejected')], default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
