# Generated by Django 2.2.10 on 2023-04-16 06:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('poker_boards', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estimate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_estimate', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('jira_ticket_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('summary', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('final_estimate', models.PositiveIntegerField()),
                ('ticket_type', models.IntegerField(choices=[(0, 'Epic'), (1, 'Story'), (2, 'Task'), (3, 'Bug'), (4, 'Subtask')])),
                ('index', models.PositiveIntegerField()),
                ('poker_board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_tickets', to='poker_boards.PokerBoard')),
                ('users', models.ManyToManyField(related_name='user_tickets', through='tickets.Estimate', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='estimate',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.Ticket'),
        ),
        migrations.AddField(
            model_name='estimate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='estimate',
            unique_together={('user', 'ticket')},
        ),
    ]
