# Generated by Django 2.2.10 on 2023-04-22 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='index',
            field=models.PositiveIntegerField(help_text='This field is used for maintaining order of ticket per board'),
        ),
    ]
