# Generated by Django 2.2.10 on 2023-04-15 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='final_estimate',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
