# Generated by Django 2.2.10 on 2023-04-28 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_auto_20230422_1113'),
        ('tickets', '0003_auto_20230422_0632'),
    ]

    operations = [
    ]
