# Generated by Django 2.2.10 on 2023-04-28 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_merge_20230426_1237'),
        ('tickets', '0004_merge_20230428_0626'),
    ]

    operations = [
    ]
